### ISSUE TITLE
Laravel Integaration

### ISSUE THREAD

**Issue by larigyn** [DucThanhNguyen/MaterialAdminLTE#7]
Sir, I wanted to integrate this into laravel project but I have some issues when compiling the less file. Do you have any tutorials or steps on how to? I have look into some of the less files but still no luck at all. Thanks

**Comment by acacha** [comment]
Maybe it could help you https://github.com/acacha/adminlte-laravel . No applied to this package (material) but works with original adminlte

**Comment by DucThanhNguyen** [comment]
I used [Visual Code](https://code.visualstudio.com/) with the extension [Easy LESS](https://marketplace.visualstudio.com/items?itemName=mrcrowl.easy-less) installed to auto-compile LESS to CSS on save. On the top of the LESS file you can see the config for output path, e.g: 
`// out: ../../dist/css/MaterialAdminLTE.min.css, compress: true, sourceMap: false`
You can also use any LESS compiler to generate CSS files but you need to config the output file to the right place.
